### PR TITLE
Make a countries index web app

### PR DESCRIPTION
**Pull request by shasherazi**
In this project:

- I fetched the countries data from [restcountries](https://restcountries.com/)
- The home page shows a grid of cards for each country
    - The card has the country name, country flag emoji, and its continent
- The user can filter countries by continent through the top dropdown menu
- Clicking on a country card opens a country details page
    - The country details page shows the capital, population, area, and timezones of the country
 
You can see the walkthrough video of the web app [here](https://www.loom.com/share/c3ae7ec487154d0983051dd8c12f6251).

### CODE REVIEW

**Review by muneebulrehman — COMMENTED** [review]
Hi @shasherazi , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is following Github flow instead of Gitflow. You were supposed to raise PR from **some_branch** into **dev** and not from **dev** into **main**.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by shasherazi** [comment]
Hi @muneebulrehman. I might be wrong, but I have been opening a PR from the dev branch to the main branch when submitting my capstones for the final review, and no reviewer has asked for any changes. I did some digging in the old lessons and found this.

image

I assume you were a bit confused, and I'll submit this PR again for review.

**Comment by rloterh** [comment]
Hi @shasherazi 
Kindly note that the steps you're referring above is meant for a **group capstone project**, which actually not applicable to capstone projects done by an individual contributor.

Cheers! 😃

**Review by rloterh — COMMENTED** [review]
Hi shasherazi, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has incorrect gitflow/ GitHub flow. Kindly note that the merge request for this activity should flow **from feature into development**. Kindly use the correct gitflow and request another code review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by shasherazi** [comment]
I have seen my peers get accepted with this tho. For example 
image

Also, wouldn't this be the most logical approach, @rloterh? `main` branch is for the most stable production-ready software build, which I'm requesting to review?

**Comment by shasherazi** [comment]
Oh ok, I understand. Thanks for the clarification

**Pull request closed without merging**
